# Default log level for all loggers
org.slf4j.simpleLogger.defaultLogLevel=warn

# Log level for a specific package
org.slf4j.simpleLogger.log.me.jaehyeon=debug

# Show date and time
org.slf4j.simpleLogger.showDateTime=true

# Format for date and time
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss.SSS

# Show the thread name
org.slf4j.simpleLogger.showThreadName=false