version: "3.5"

services:
  jobmanager:
    image: pyflink:1.15.2-scala_2.12
    container_name: jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
        rest.flamegraph.enabled: true
        web.backpressure.refresh-interval: 10000
      - RUNTIME_ENV=DOCKER
      - BOOTSTRAP_SERVERS=$BOOTSTRAP_SERVERS
    volumes:
      - $PWD:/etc/flink
  taskmanager:
    image: pyflink:1.15.2-scala_2.12
    container_name: taskmanager
    command: taskmanager
    volumes:
      - flink_data:/tmp/
      - $PWD:/etc/flink
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 3
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
      - RUNTIME_ENV=DOCKER
      - BOOTSTRAP_SERVERS=$BOOTSTRAP_SERVERS
    depends_on:
      - jobmanager

volumes:
  flink_data:
    driver: local
    name: flink_data
