version: "3.5"

services:
  jobmanager:
    image: confluent-flink-101:1.15.4
    command: jobmanager
    ports:
      - "8081:8081"
    networks:
      - kafkanet
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
        rest.flamegraph.enabled: true
        web.backpressure.refresh-interval: 10000
  taskmanager:
    image: confluent-flink-101:1.15.4
    command: taskmanager
    networks:
      - kafkanet
    volumes:
      - flink_data:/tmp/
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 3
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
    depends_on:
      - jobmanager
  sql-client:
    image: confluent-flink-101:1.15.4
    command: bin/sql-client.sh
    networks:
      - kafkanet
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    depends_on:
      - jobmanager

networks:
  kafkanet:
    external: true
    name: kafka-network

volumes:
  flink_data:
